#!/usr/bin/env python3
"""
Code File Generator Tool
A comprehensive Python-based tool that generates code files with appropriate 
language extensions and template code for various programming languages.
"""

import os
import sys
import argparse
from pathlib import Path


# Template code for each supported language
TEMPLATES = {
    'python': {
        'extension': '.py',
        'template': '''#!/usr/bin/env python3
"""
{filename} - Python Script
Author: Generated by Code Generator
Date: {date}
"""


def main():
    """
    Main function - entry point of the script
    """
    print("Hello from Python!")
    # Add your code here
    pass


if __name__ == "__main__":
    main()
'''
    },
    'javascript': {
        'extension': '.js',
        'template': '''/**
 * {filename} - JavaScript File
 * Author: Generated by Code Generator
 * Date: {date}
 */

/**
 * Main function - entry point of the script
 */
function main() {{
    console.log("Hello from JavaScript!");
    // Add your code here
}}

// Execute main function
main();
'''
    },
    'typescript': {
        'extension': '.ts',
        'template': '''/**
 * {filename} - TypeScript File
 * Author: Generated by Code Generator
 * Date: {date}
 */

/**
 * Main function - entry point of the script
 */
function main(): void {{
    console.log("Hello from TypeScript!");
    // Add your code here
}}

// Execute main function
main();
'''
    },
    'java': {
        'extension': '.java',
        'template': '''/**
 * {filename} - Java Class
 * Author: Generated by Code Generator
 * Date: {date}
 */

public class {classname} {{
    
    /**
     * Main method - entry point of the program
     * @param args command line arguments
     */
    public static void main(String[] args) {{
        System.out.println("Hello from Java!");
        // Add your code here
    }}
    
    /**
     * Example method
     * @return greeting message
     */
    public String greet() {{
        return "Hello, World!";
    }}
}}
'''
    },
    'cpp': {
        'extension': '.cpp',
        'template': '''/**
 * {filename} - C++ Source File
 * Author: Generated by Code Generator
 * Date: {date}
 */

#include <iostream>
#include <string>

using namespace std;

/**
 * Main function - entry point of the program
 * @return exit status
 */
int main() {{
    cout << "Hello from C++!" << endl;
    // Add your code here
    return 0;
}}

/**
 * Example function
 * @return greeting message
 */
string greet() {{
    return "Hello, World!";
}}
'''
    },
    'go': {
        'extension': '.go',
        'template': '''/**
 * {filename} - Go Source File
 * Author: Generated by Code Generator
 * Date: {date}
 */

package main

import (
    "fmt"
)

/**
 * main - entry point of the program
 */
func main() {{
    fmt.Println("Hello from Go!")
    // Add your code here
}}

/**
 * greet - example function
 * @return greeting message
 */
func greet() string {{
    return "Hello, World!"
}}
'''
    },
    'rust': {
        'extension': '.rs',
        'template': '''/**
 * {filename} - Rust Source File
 * Author: Generated by Code Generator
 * Date: {date}
 */

/**
 * Main function - entry point of the program
 */
fn main() {{
    println!("Hello from Rust!");
    // Add your code here
}}

/**
 * Example function
 * Returns a greeting message
 */
fn greet() -> String {{
    String::from("Hello, World!")
}}
'''
    },
    'php': {
        'extension': '.php',
        'template': '''<?php
/**
 * {filename} - PHP Script
 * Author: Generated by Code Generator
 * Date: {date}
 */

/**
 * Main function - entry point of the script
 */
function main() {{
    echo "Hello from PHP!\\n";
    // Add your code here
}}

/**
 * Example function
 * @return string greeting message
 */
function greet() {{
    return "Hello, World!";
}}

// Execute main function
main();
?>
'''
    },
    'ruby': {
        'extension': '.rb',
        'template': '''#!/usr/bin/env ruby
# {filename} - Ruby Script
# Author: Generated by Code Generator
# Date: {date}

##
# Main function - entry point of the script
def main
  puts "Hello from Ruby!"
  # Add your code here
end

##
# Example function
# @return [String] greeting message
def greet
  "Hello, World!"
end

# Execute main function
main if __FILE__ == $PROGRAM_NAME
'''
    },
    'swift': {
        'extension': '.swift',
        'template': '''/**
 * {filename} - Swift Source File
 * Author: Generated by Code Generator
 * Date: {date}
 */

import Foundation

/**
 * Main function - entry point of the program
 */
func main() {{
    print("Hello from Swift!")
    // Add your code here
}}

/**
 * Example function
 * - Returns: greeting message
 */
func greet() -> String {{
    return "Hello, World!"
}}

// Execute main function
main()
'''
    }
}


def get_current_date():
    """Get current date in formatted string"""
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d")


def get_classname_from_filename(filename):
    """
    Convert filename to a valid class name (for Java)
    Removes extension and ensures it's a valid identifier
    """
    # Remove extension if present
    name = filename.replace('.java', '')
    
    # If already in PascalCase or camelCase, return as is (capitalize first letter)
    if name and name[0].isupper():
        return name
    
    # Otherwise convert to PascalCase (capitalize first letter and after underscores/hyphens)
    parts = name.replace('-', '_').split('_')
    return ''.join(word.capitalize() for word in parts if word)


def create_file(language, filename, output_dir='.'):
    """
    Create a code file with the appropriate template
    
    Args:
        language: Programming language (python, javascript, etc.)
        filename: Name of the file to create (without extension)
        output_dir: Directory where the file will be created
        
    Returns:
        tuple: (success: bool, message: str)
    """
    language = language.lower()
    
    # Validate language
    if language not in TEMPLATES:
        return False, f"Error: Unsupported language '{language}'"
    
    # Get template info
    template_info = TEMPLATES[language]
    extension = template_info['extension']
    template = template_info['template']
    
    # Add extension if not present
    if not filename.endswith(extension):
        full_filename = filename + extension
    else:
        full_filename = filename
    
    # Create output directory if it doesn't exist
    try:
        os.makedirs(output_dir, exist_ok=True)
    except Exception as e:
        return False, f"Error: Could not create directory '{output_dir}': {str(e)}"
    
    # Full path to the output file
    filepath = os.path.join(output_dir, full_filename)
    
    # Check if file already exists
    if os.path.exists(filepath):
        return False, f"Error: File '{filepath}' already exists"
    
    # Prepare template variables
    classname = get_classname_from_filename(full_filename) if language == 'java' else ''
    
    # Format template
    content = template.format(
        filename=full_filename,
        date=get_current_date(),
        classname=classname
    )
    
    # Write file
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True, f"Success: Created '{filepath}'"
    except Exception as e:
        return False, f"Error: Could not write file '{filepath}': {str(e)}"


def interactive_mode():
    """
    Run the tool in interactive mode with menu
    """
    print("\n" + "="*60)
    print("  Code File Generator Tool")
    print("="*60)
    print("\nSupported Languages:")
    
    languages = list(TEMPLATES.keys())
    for i, lang in enumerate(languages, 1):
        ext = TEMPLATES[lang]['extension']
        print(f"  {i}. {lang.capitalize():<15} ({ext})")
    
    print("\n" + "-"*60)
    
    # Get language selection
    while True:
        try:
            choice = input("\nSelect language (1-10) or 'q' to quit: ").strip()
            
            if choice.lower() == 'q':
                print("Goodbye!")
                return
            
            choice_num = int(choice)
            if 1 <= choice_num <= len(languages):
                language = languages[choice_num - 1]
                break
            else:
                print(f"Error: Please enter a number between 1 and {len(languages)}")
        except ValueError:
            print("Error: Please enter a valid number or 'q' to quit")
    
    # Get filename
    while True:
        filename = input(f"\nEnter filename (without extension): ").strip()
        if filename:
            break
        print("Error: Filename cannot be empty")
    
    # Get output directory (optional)
    output_dir = input("Enter output directory (press Enter for current directory): ").strip()
    if not output_dir:
        output_dir = '.'
    
    # Create the file
    success, message = create_file(language, filename, output_dir)
    print(f"\n{message}")
    
    if success:
        print("\n✓ File created successfully!")
    else:
        print("\n✗ File creation failed!")


def main():
    """
    Main function - entry point of the tool
    """
    parser = argparse.ArgumentParser(
        description='Code File Generator - Generate code files with templates for various languages',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # Interactive mode
  python code_generator.py
  
  # Generate Python file
  python code_generator.py -l python -f my_script
  
  # Generate Java file in specific directory
  python code_generator.py -l java -f MyClass -o src/main/java
  
  # List supported languages
  python code_generator.py --list

Supported Languages:
  python, javascript, typescript, java, cpp, go, rust, php, ruby, swift
        '''
    )
    
    parser.add_argument(
        '-l', '--language',
        help='Programming language',
        choices=list(TEMPLATES.keys()),
        metavar='LANG'
    )
    
    parser.add_argument(
        '-f', '--filename',
        help='Name of the file to create (without extension)',
        metavar='NAME'
    )
    
    parser.add_argument(
        '-o', '--output',
        help='Output directory (default: current directory)',
        default='.',
        metavar='DIR'
    )
    
    parser.add_argument(
        '--list',
        action='store_true',
        help='List all supported languages and exit'
    )
    
    # Parse arguments
    args = parser.parse_args()
    
    # Handle --list flag
    if args.list:
        print("\nSupported Languages:")
        for lang, info in sorted(TEMPLATES.items()):
            print(f"  {lang:<15} {info['extension']}")
        return 0
    
    # If language and filename provided, use CLI mode
    if args.language and args.filename:
        success, message = create_file(args.language, args.filename, args.output)
        print(message)
        return 0 if success else 1
    
    # If only partial arguments provided, show error
    elif args.language or args.filename:
        print("Error: Both --language and --filename are required for CLI mode")
        print("Run with --help for usage information")
        print("Or run without arguments for interactive mode")
        return 1
    
    # Otherwise, run interactive mode
    else:
        try:
            interactive_mode()
            return 0
        except KeyboardInterrupt:
            print("\n\nInterrupted by user. Goodbye!")
            return 0
        except Exception as e:
            print(f"\nError: {str(e)}")
            return 1


if __name__ == "__main__":
    sys.exit(main())
